# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ('first_name', 'last_name')},
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default=b'TEXT', verbose_name=b'article text'),
        ),
    ]
