# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Content')),
                ('caption', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
            ],
            bases=('content.content',),
        ),
        migrations.AddField(
            model_name='article',
            name='headline',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
