# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='year',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
