# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
