# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170311_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='favorite_album',
            field=models.CharField(default='Abbey Road', max_length=50),
            preserve_default=False,
        ),
    ]
