# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20171027_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contributors',
            field=models.ManyToManyField(to='content.Contributor'),
        ),
    ]
